ProyectoTerminal/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTerminal.Models;

namespace ProyectoTerminal.Controllers
{
    public class NotaController : Controller
    {
        private ProyectoTerminalContext db = new ProyectoTerminalContext();

        // GET: /Nota/
        public ActionResult Index(Guid pId)
        {
            var notas = db.Notas.Where(n => n.ProyectoId == pId);

            return View(notas.ToList());
        }

        // GET: /Nota/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Notas.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // GET: /Nota/Create
        public ActionResult Create(Guid pId)
        {
            var nota = new Nota
            {
                ProyectoId = pId
            };
            return View(nota);
        }

        // POST: /Nota/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Texto,Fecha,ProyectoId")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                nota.Id = Guid.NewGuid();
                nota.Fecha = DateTime.Now;
                db.Notas.Add(nota);
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = nota.ProyectoId });
            }

            return View(nota);
        }

        // GET: /Nota/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Notas.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // POST: /Nota/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Texto,Fecha,ProyectoId")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nota).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = nota.ProyectoId });
            }
            return View(nota);
        }

        // GET: /Nota/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Notas.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // POST: /Nota/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Nota nota = db.Notas.Find(id);
            db.Notas.Remove(nota);
            db.SaveChanges();
            return RedirectToAction("Index", new { pId = nota.ProyectoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoTerminal/Controllers/ProyectoController.cs
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using ProyectoTerminal.Models;

namespace ProyectoTerminal.Controllers
{
    [Authorize]
    public class ProyectoController : Controller
    {
        private ProyectoTerminalContext db = new ProyectoTerminalContext();

        // GET: /Proyecto/
        public ActionResult Index()
        {
            return View(db.Proyectoes.ToList());
        }

        // GET: /Proyecto/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proyecto proyecto = db.Proyectoes.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            return View(proyecto);
        }

        // GET: /Proyecto/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: /Proyecto/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Nombre,Fecha,Activo,Descripcion")] Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                proyecto.Id = Guid.NewGuid();
                proyecto.Fecha = DateTime.Now;
                proyecto.Activo = true;
                db.Proyectoes.Add(proyecto);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(proyecto);
        }

        // GET: /Proyecto/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proyecto proyecto = db.Proyectoes.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            return View(proyecto);
        }

        // POST: /Proyecto/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Nombre,Fecha,Activo,Descripcion")] Proyecto proyecto)
        {
            if (ModelState.IsValid)
            {
                db.Entry(proyecto).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(proyecto);
        }

        // GET: /Proyecto/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Proyecto proyecto = db.Proyectoes.Find(id);
            if (proyecto == null)
            {
                return HttpNotFound();
            }
            return View(proyecto);
        }

        // POST: /Proyecto/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Proyecto proyecto = db.Proyectoes.Find(id);
            db.Proyectoes.Remove(proyecto);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoTerminal/Views/Nota/Create.cshtml
@model ProyectoTerminal.Models.Nota

@{
    ViewBag.Title = "Crear nueva nota";
}

<h2>Crear nueva nota</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Nota</h4>
        <hr />
        @Html.ValidationSummary(true)

        @Html.HiddenFor(t => t.ProyectoId)

        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.Texto, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Texto)
                    @Html.ValidationMessageFor(model => model.Texto)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Crear" class="btn btn-success" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index", new { pId = Model.ProyectoId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoTerminal/Views/Nota/Delete.cshtml
@model ProyectoTerminal.Models.Nota

@{
    ViewBag.Title = "Borrar nota";
}

<h2>Borrar la nota</h2>

<h3>Esta seguro que desea borrar esta nota?</h3>
<div>
    <h4>Nota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Texto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Texto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar a la lista", "Index", new { pId = Model.ProyectoId }, new { @class = "btn btn-info" })
        </div>
    }
</div>

ProyectoTerminal/Views/Nota/Details.cshtml
@model ProyectoTerminal.Models.Nota

@{
    ViewBag.Title = "Detalles de la nota";
}

<h2>Detalles de la nota</h2>

<div>
    <h4>Nota</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Texto)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Texto)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-info" }) |
    @Html.ActionLink("Regresar a la lista", "Index", new { pId = Model.ProyectoId }, new { @class = "btn btn-info" })
</p>

ProyectoTerminal/Views/Nota/Edit.cshtml
@model ProyectoTerminal.Models.Nota

@{
    ViewBag.Title = "Editar Nota";
}

<h2>Editar la Nota</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Nota</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(t => t.ProyectoId)

        <div class="form-group">
            @Html.LabelFor(model => model.Texto, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Texto)
                @Html.ValidationMessageFor(model => model.Texto)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
   @Html.ActionLink("Regresar a la lista", "Index", new { pId = Model.ProyectoId })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoTerminal/Views/Nota/Index.cshtml
@using ProyectoTerminal.Extensions
@model IEnumerable<ProyectoTerminal.Models.Nota>

@{
    ViewBag.Title = "Listado de Notas";
}

<h2>Notas</h2>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Texto)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Texto).ToString().TruncateString(0, 100)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil" }) |
                @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" }) |
                @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "glyphicon glyphicon-trash" })
            </td>
        </tr>
    }

</table>

@Html.ActionLink("Regresar a la lista de proyectos", "Index", "Proyecto", null, new { @class = "btn btn-info" })