ProyectoTerminal/Controllers/DocumentoController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTerminal.Models;

namespace ProyectoTerminal.Controllers
{
    public class DocumentoController : Controller
    {
        private ProyectoTerminalContext db = new ProyectoTerminalContext();

        // GET: /Documento/
        public ActionResult Index(Guid pId)
        {
            var docs = db.Documentoes.Where(d => d.ProyectoId == pId);
            return View(docs.ToList());
        }

        // GET: /Documento/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documento documento = db.Documentoes.Find(id);
            if (documento == null)
            {
                return HttpNotFound();
            }
            return View(documento);
        }

        // GET: /Documento/Create
        public ActionResult Create(Guid pId)
        {
            var doc = new Documento
            {
                ProyectoId = pId
            };
            return View(doc);
        }

        // POST: /Documento/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,ProyectoId,Titulo,Texto")] Documento documento)
        {
            if (ModelState.IsValid)
            {
                documento.Id = Guid.NewGuid();
                
                db.Documentoes.Add(documento);
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = documento.ProyectoId });
            }

            return View(documento);
        }

        // GET: /Documento/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documento documento = db.Documentoes.Find(id);
            if (documento == null)
            {
                return HttpNotFound();
            }
            return View(documento);
        }

        // POST: /Documento/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,ProyectoId,Titulo,Texto")] Documento documento)
        {
            if (ModelState.IsValid)
            {
                db.Entry(documento).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = documento.ProyectoId });
            }
            return View(documento);
        }

        // GET: /Documento/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Documento documento = db.Documentoes.Find(id);
            if (documento == null)
            {
                return HttpNotFound();
            }
            return View(documento);
        }

        // POST: /Documento/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Documento documento = db.Documentoes.Find(id);
            db.Documentoes.Remove(documento);
            db.SaveChanges();
            return RedirectToAction("Index", new { pId = documento.ProyectoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoTerminal/Controllers/MetaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTerminal.Models;

namespace ProyectoTerminal.Controllers
{
    public class MetaController : Controller
    {
        private ProyectoTerminalContext db = new ProyectoTerminalContext();

        // GET: /Meta/
        public ActionResult Index(Guid pId)
        {
            var metas = db.Metas.Where(n => n.ProyectoId == pId);
            return View(metas.ToList());
        }

        // GET: /Meta/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meta meta = db.Metas.Find(id);
            if (meta == null)
            {
                return HttpNotFound();
            }
            return View(meta);
        }

        // GET: /Meta/Create
        public ActionResult Create(Guid pId)
        {
            var meta = new Meta
            {
                ProyectoId = pId,
                FechaCompletacionPlaneada = DateTime.Now

            };
            return View(meta);
        }

        // POST: /Meta/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,FechaCompletacionPlaneada,Nombre,FechaCompletacionActual,Completada,ProyectoId")] Meta meta)
        {
            if (ModelState.IsValid)
            {
                meta.Id = Guid.NewGuid();
                db.Metas.Add(meta);
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = meta.ProyectoId });
            }

            return View(meta);
        }

        // GET: /Meta/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meta meta = db.Metas.Find(id);
            if (meta == null)
            {
                return HttpNotFound();
            }
            return View(meta);
        }

        // POST: /Meta/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,FechaCompletacionPlaneada,Nombre,FechaCompletacionActual,Completada,ProyectoId")] Meta meta)
        {
            if (ModelState.IsValid)
            {
                
                if (meta.FechaCompletacionActual != null)
                {
                    meta.Completada = true;
                }

                db.Entry(meta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = meta.ProyectoId });
            }
            return View(meta);
        }

        // GET: /Meta/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Meta meta = db.Metas.Find(id);
            if (meta == null)
            {
                return HttpNotFound();
            }
            return View(meta);
        }

        // POST: /Meta/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Meta meta = db.Metas.Find(id);
            db.Metas.Remove(meta);
            db.SaveChanges();
            return RedirectToAction("Index", new { pId = meta.ProyectoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoTerminal/Controllers/NotaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTerminal.Models;

namespace ProyectoTerminal.Controllers
{
    public class NotaController : Controller
    {
        private ProyectoTerminalContext db = new ProyectoTerminalContext();

        // GET: /Nota/
        public ActionResult Index(Guid pId)
        {
            var notas = db.Notas.Where(n => n.ProyectoId == pId);

            return View(notas.ToList());
        }

        // GET: /Nota/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Notas.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // GET: /Nota/Create
        public ActionResult Create(Guid pId)
        {
            var nota = new Nota
            {
                ProyectoId = pId
            };
            return View(nota);
        }

        // POST: /Nota/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Texto,Fecha,ProyectoId")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                nota.Id = Guid.NewGuid();
                nota.Fecha = DateTime.Now;
                db.Notas.Add(nota);
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = nota.ProyectoId });
            }

            return View(nota);
        }

        // GET: /Nota/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Notas.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // POST: /Nota/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Texto,Fecha,ProyectoId")] Nota nota)
        {
            if (ModelState.IsValid)
            {
                db.Entry(nota).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = nota.ProyectoId });
            }
            return View(nota);
        }

        // GET: /Nota/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Nota nota = db.Notas.Find(id);
            if (nota == null)
            {
                return HttpNotFound();
            }
            return View(nota);
        }

        // POST: /Nota/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Nota nota = db.Notas.Find(id);
            db.Notas.Remove(nota);
            db.SaveChanges();
            return RedirectToAction("Index", new { pId = nota.ProyectoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoTerminal/Controllers/TareasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ProyectoTerminal.Models;

namespace ProyectoTerminal.Controllers
{
    public class TareasController : Controller
    {
        private ProyectoTerminalContext db = new ProyectoTerminalContext();

        // GET: /Tareas/
        public ActionResult Index(Guid pId)
        {
            var tareas = db.Tareas.Where(n => n.ProyectoId == pId);
            return View(tareas.ToList());
        }

        // GET: /Tareas/Details/5
        public ActionResult Details(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tareas.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // GET: /Tareas/Create
        public ActionResult Create(Guid pId)
        {
            var tarea = new Tarea
            {
                ProyectoId = pId
            };
            return View(tarea);
        }

        // POST: /Tareas/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include="Id,Nombre,Descripcion,ProyectoId,Activa")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                tarea.Id = Guid.NewGuid();
                tarea.Activa = true;
                db.Tareas.Add(tarea);
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = tarea.ProyectoId });
            }

            return View(tarea);
        }

        // GET: /Tareas/Edit/5
        public ActionResult Edit(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tareas.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: /Tareas/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include="Id,Nombre,Descripcion,ProyectoId,Activa")] Tarea tarea)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tarea).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index", new { pId = tarea.ProyectoId });
            }
            return View(tarea);
        }

        // GET: /Tareas/Delete/5
        public ActionResult Delete(Guid? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Tarea tarea = db.Tareas.Find(id);
            if (tarea == null)
            {
                return HttpNotFound();
            }
            return View(tarea);
        }

        // POST: /Tareas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            Tarea tarea = db.Tareas.Find(id);
            db.Tareas.Remove(tarea);
            db.SaveChanges();
            return RedirectToAction("Index", new { pId = tarea.ProyectoId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

ProyectoTerminal/Views/Proyecto/Create.cshtml
@model ProyectoTerminal.Models.Proyecto

@{
    ViewBag.Title = "Crear nuevo proyecto";
}

<h2>Crear nuevo proyecto</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Nombre)
                    @Html.ValidationMessageFor(model => model.Nombre)
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Descripcion, new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextAreaFor(model => model.Descripcion)
                    @Html.ValidationMessageFor(model => model.Descripcion)
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Crear" class="btn btn-sucess" />
                </div>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoTerminal/Views/Proyecto/Delete.cshtml
@model ProyectoTerminal.Models.Proyecto

@{
    ViewBag.Title = "Borrar proyecto";
}

<h2>Borrar proyecto</h2>

<h3>Esta seguro que desea borrar este proyecto?</h3>
<div>
    <h4>Proyecto</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Borrar" class="btn btn-danger" /> |
            @Html.ActionLink("Regresar a la lista", "Index", null, new { @class = "btn btn-info" })
        </div>
    }
</div>

ProyectoTerminal/Views/Proyecto/Details.cshtml
@model ProyectoTerminal.Models.Proyecto

@{
    ViewBag.Title = "Detalles del proyecto";
}

<h2>Detalles</h2>

<div>
    <h4>Proyecto</h4>
	<hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nombre)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nombre)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Fecha)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Fecha)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Activo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Activo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Descripcion)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Descripcion)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-info" }) |
    @Html.ActionLink("Regresar a la lista", "Index", null, new { @class = "btn btn-info" })
</p>

ProyectoTerminal/Views/Proyecto/Edit.cshtml
@model ProyectoTerminal.Models.Proyecto

@{
    ViewBag.Title = "Editar proyecto";
}

<h2>Editar proyecto</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Proyecto</h4>
        <hr />
        @Html.ValidationSummary(true)
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nombre, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nombre)
                @Html.ValidationMessageFor(model => model.Nombre)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Fecha, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Fecha)
                @Html.ValidationMessageFor(model => model.Fecha)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Activo, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Activo)
                @Html.ValidationMessageFor(model => model.Activo)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Descripcion, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextAreaFor(model => model.Descripcion)
                @Html.ValidationMessageFor(model => model.Descripcion)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a la lista", "Index", null, new { @class = "btn btn-info" })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ProyectoTerminal/Views/Proyecto/Index.cshtml
@using ProyectoTerminal.Extensions
@model IEnumerable<ProyectoTerminal.Models.Proyecto>

@{
    ViewBag.Title = "Listado de Proyectos";
}

<h2>Listado de proyectos</h2>

<p>
    @Html.ActionLink("Crear nuevo proyecto", "Create", null, new { @class = "btn btn-success" })
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Activo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Notas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Requerimientos)
        </th>
        <th class="center-block">
            @Html.DisplayNameFor(model => model.Documentos)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Metas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Tareas)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Repositorios)
        </th>
        <th>
            Acciones
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nombre).ToString().TruncateString(0, 100)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Activo)
        </td>
        <td>
            <!-- notas -->
            @Html.ActionLink(" ", "Index", "Nota", new { pid = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" }) |
            @Html.ActionLink(" ", "Create", "Nota", new {pid = item.Id}, new { @class = "glyphicon glyphicon-plus" })
        </td>
        <td> <!-- requerimientos -->
            @Html.ActionLink(" ", "Index", "Requerimiento", new { pid = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" })
            @Html.ActionLink(" ", "Create", "Requerimiento", new { pid = item.Id }, new { @class = "glyphicon glyphicon-plus" })
        </td>
        <td class="center-block">
            <!-- documentos -->
            @Html.ActionLink(" ", "Index", "Documento", new { pid = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" })
            @Html.ActionLink(" ", "Create", "Documento", new { pid = item.Id }, new { @class = "glyphicon glyphicon-plus" })
        </td>
        <td>
            <!-- metas -->
            @Html.ActionLink(" ", "Index", "Meta", new { pid = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" })
            @Html.ActionLink(" ", "Create", "Meta", new { pid = item.Id }, new { @class = "glyphicon glyphicon-plus" })
        </td>
        <td>
            <!-- tareas -->
            @Html.ActionLink(" ", "Index", "Tareas", new { pid = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" })
            @Html.ActionLink(" ", "Create", "Tareas", new { pid = item.Id }, new { @class = "glyphicon glyphicon-plus" })
        </td>
        <td>
            <!-- repositorios -->
            @Html.ActionLink(" ", "Index", "Repositorios", new { pid = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" }) |
            @Html.ActionLink(" ", "Create", "Repositorios", new { pid = item.Id }, new { @class = "glyphicon glyphicon-plus" })
        </td>
        <td>
            @Html.ActionLink(" ", "Edit", new { id = item.Id }, new { @class = "glyphicon glyphicon-pencil" }) |
            @Html.ActionLink(" ", "Details", new { id = item.Id }, new { @class = "glyphicon glyphicon-zoom-in" }) |
            @Html.ActionLink(" ", "Delete", new { id = item.Id }, new { @class = "glyphicon glyphicon-remove" })
        </td>
    </tr>
}

</table>